### ISSUE TITLE
Link up/down events generated more than once

### ISSUE THREAD

**Issue by ajoaoff** [kytos/mef_eline#100]
Link up/down events are generated more than once (for each interface in the link), causing a race condition.

**Comment by beraldoleal** [comment]
@ajoaoff this events are generated here or on kytos/topology ?

**Comment by ajoaoff** [comment]
kytos/topology only generates topology update events, they are generated on kytos/of_core

**Comment by beraldoleal** [comment]
@ajoaoff ok, so, we should move this to of_core repository, right ?

**Comment by ajoaoff** [comment]
I'm not sure if it should be on of_core or topology.

**Comment by ajoaoff** [comment]
Fixed in 382c22bb0d14.
