### ISSUE TITLE
Fix mef-eline tests with scrutinizer

### ISSUE THREAD

**Issue by rmotitsuki** [kytos/mef_eline#106]
Fix unit tests failing with Scrutinizer

**Comment by rmotitsuki** [comment]
Running the command tox generate multiple errors like:

```
  File "/home/scrutinizer/build/tests/models/test_evc_base.py", line 11, in <module>
    from napps.kytos.mef_eline.models import EVC
ModuleNotFoundError: No module named 'napps'
```

**Comment by rmotitsuki** [comment]
Tried adding to tox.ini the following lines.
```
setenv=
   PYTHONPATH = {toxworkdir}/py36/var/lib/kytos/:{envdir}
```

It worked in my machine, but failed in the @ajoaoff machine.
I will create a new virtual environment to check the solution in a clean environment.

**Comment by rmotitsuki** [comment]
I missed out a piece of information in my comment.
The line must be included in **[testenv]** section.
@ajoaoff tested successfully now.

**Comment by hdiogenes** [comment]
@rmotitsuki's solution worked. Closing the issue.
