### ISSUE TITLE
EVC schedule accepts any parameter as job action

### ISSUE THREAD

**Issue by rmotitsuki** [kytos/mef_eline#139]
In EVC CircuitSchedule the action property must have the values 'create' or 'remove' to properly trigger the cron job action inside the Scheduler, but it is accepting any kind of string.
When the Scheduler uses it, the invalid action value will trigger "None" as a cron job.

To fix this issue the developer must pay attention where he/she will put the value check, because the CircuitSchedule is saved in the Storehouse, and it is possible that some of them already have invalid values to the action property.
If the check happens during the instantiation throwing an Exception, the system will never retrieve the class from the Storehouse.

**Comment by rmotitsuki** [comment]
Example of a CircuitSchedule saved in the Storehouse.
The "action" should be "create" or "remove".

```
      {
        "action": "string",
        "frequency": "15 * * * *",
        "id": "c28c81fb23554b8686f64ebe1054ca94"
      }
```

**Comment by ajoaoff** [comment]
I think it is probably better to silently discard the `CircuitSchedule` with invalid action.
