### ISSUE TITLE
Circuit is not deployed if both UNIs are in the same switch

### ISSUE THREAD

**Issue by ajoaoff** [kytos/mef_eline#185]
If the circuit connects two UNIs in the same switch, the deployment should consist of 2 flows in that switch, but nothing is done is that case.

**Comment by italovalcy** [comment]
Hi Antonio,

I still cannot create the intra-switch EVC. I'm using kytos/nightly docker image + mef_eline from the master branch:
```
kytosd -E -f
mn --topo single,3 --controller=remote,ip=172.20.0.2
curl -s -X POST -d '{"name": "my evc3","enabled": true, "uni_a": { "interface_id": "00:00:00:00:00:00:00:01:1" }, "uni_z": {"interface_id": "00:00:00:00:00:00:00:01:2"}}' http://172.20.0.2:8181/api/kytos/mef_eline/v2/evc/ -H "Content-Type: application/json"
mininet> sh ovs-ofctl dump-flows s1
 cookie=0x0, duration=28.930s, table=0, n_packets=0, n_bytes=0, priority=1000,dl_vlan=3799,dl_type=0x88cc actions=CONTROLLER:65535
```

Can you please help me figure out what I'm doing wrong?

**Comment by ajoaoff** [comment]
Hi, Italo. This looks like a déjà vu for me. The problem is related to `dynamic_backup_path` not being set. Take a look at #198.

**Comment by italovalcy** [comment]
Hi Antonio,

I've already tried to create the circuit with the option
dynamic_backup_path:true but the same error (sorry to not mention on the
first place):

# kytosd -E -f
# mn --topo single,3 --controller=remote,ip=172.18.0.2

$ curl -s -X POST -d '{"name": "my evc3","enabled":
true,"dynamic_backup_path":true, "uni_a": { "interface_id":
"00:00:00:00:00:00:00:01:1", "tag": {"tag_type":1,"value": 101} }, "uni_z":
{"interface_id": "00:00:00:00:00:00:00:01:2", "tag": {"tag_type":
1,"value": 101}}}' http://172.18.0.2:8181/api/kytos/mef_eline/v2/evc/ -H
"Content-Type: application/json"
{"circuit_id":"ceb3cab794be44d6ab3942c634b32093"}

mininet> sh ovs-ofctl dump-flows s1
 cookie=0x0, duration=61.245s, table=0, n_packets=0, n_bytes=0,
priority=1000,dl_vlan=3799,dl_type=0x88cc actions=CONTROLLER:65535

I've also tried using no tags, using tag on one side and not in the other,
same behavior.

Thanks, Italo

**Comment by ajoaoff** [comment]
Changes made later broke a part of the code dealing with circuits where both UNIs are in the same switch.
