### ISSUE TITLE
Generating payload and submitting evc request giving 400 error code

### ISSUE THREAD

**Issue by dgarc330** [kytos/mef_eline#213]
We are getting error 400, and the Exception("Status code is not 200") from generating this payload:

{'name': 'evc_410', 'uni_a': {'interface_id': '00:00:00:00:00:00:00:01:16', 'tag': {'tag_type': 1, 'value': 410}}, 'uni_z': {'interface_id': '00:00:00:00:00:00:00:01:15', 'tag': {'tag_type': 1, 'value': 410}}, 'dynamic_backup_path': True, 'enabled': True}

We tried tag_type and value as both, a string and and integer but we are always getting this error back. this is how we are generating our payload and submitting the request:

```
def generate_payload(evc_name, uni_a, uni_z, vlan, primary_path=[], backup_path=[], dynamic_backup_path=True):
    """Function to create the payload content to create an EVC"""
    payload = {
        "name": evc_name,
        "uni_a": {
            "interface_id": uni_a,
            "tag": {
                "tag_type": 1,
                "value": int(vlan)
            }
        },
        "uni_z": {
            "interface_id": uni_z,
            "tag": {
                "tag_type": 1,
                "value": int(vlan)
            }
        },
        # "primary_path": primary_path,
        # "backup_path": backup_path,
        "dynamic_backup_path": dynamic_backup_path,
        "enabled": True
    }
    print(json.dumps(payload))
    return payload

def submit_request(settings, payload):
    """Confirm sEVC was created and enabled by Kytos"""
    api_url = settings.KYTOS_API_URL + '/mef_eline/v2/evc/'
    new_headers = {'Content-type': 'application/json'}
    response = requests.post(api_url, data=json.dumps(payload), headers=new_headers)
    # response = requests.post(api_url, json=json.dumps(payload))
    print(response.status_code)
    if response.status_code != 200:
        raise Exception("Status code is not 200")
    evc_id = json.loads(response.content.decode("utf-8"))
    if isinstance(evc_id, dict):
        return evc_id["circuit_id"]
    else:
        raise Exception("EVC_id is not a dictionary")
```

I looked in the mef_eline documentation and I found this:
400 = Request do not have a JSON or JSON format do not match the EVC object or EVC already exists.

But at first glance we can't find where the file is not been properly parsed into JSON.

**Comment by hdiogenes** [comment]
I think the above Python code may be hiding the error message from Kytos. If I try the same request with curl I get this: 

```
$ curl --header "Content-Type: application/json" \          
  --request POST \
  --data '{"name": "evc_410", "uni_a": {"interface_id": "00:00:00:00:00:00:00:01:16", "tag": {"tag_type": 1, "value": 410}}, "uni_z": {"interface_id": "00:00:00:00:00:00:00:01:15", "tag": {"tag_type": 1, "value": 410}}, "dynamic_backup_path": true, "enabled": true}' \
  http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc/

{"code":400,"description":"Error creating UNI: Could not instantiate interface 00:00:00:00:00:00:00:01:16","name":"Bad Request"}
```

Also, the error message can be seen in the Kytos console if you start it in debug mode (`kytos -Df`):

```
2020-11-03 17:25:07,997 - DEBUG [kytos.napps.kytos/mef_eline] (Thread-25) create_circuit /v2/evc/
2020-11-03 17:25:08,003 - DEBUG [kytos.napps.kytos/mef_eline] (Thread-25) create_circuit result Error creating UNI: Could not instantiate interface 00:00:00:00:00:00:00:01:16 400
```

Please check if you get the same message, and then we can discuss what actions we need to take.

**Comment by dgarc330** [comment]
Yes, you were right about the python exception masking the real error. After submitting the request via curl like you suggested, I got the true source of the error:

`{“code”:400,“description”:“Error creating UNI: Could not instantiate interface 00:00:00:00:00:00:00:01:16”,“name”:“Bad Request”}`

**Comment by hdiogenes** [comment]
@ajoaoff can you think of a more specific error code that we could return here? If not, we could just update the API docs with this possibility.

**Comment by ajoaoff** [comment]
The only other error code I can think about is 406 - Not Acceptable.

**Comment by hdiogenes** [comment]
Well, I think it's better to leave the current code and just update the documentation, then.
