### ISSUE TITLE
EVC active status should take into account up/down interfaces

### ISSUE THREAD

**Issue by viniarck** [kytos/mef_eline#26]
As specified in the blueprint, EVC's active status should take into account up/down interfaces. For now, it does not consider interfaces down along the way (it's always active True). We should probably also add some hooks with the topology NApp events for PortStats to update this asynchronously.

**Comment by beraldoleal** [comment]
Lets split into two issues.

**Comment by viniciusarcanjo** [comment]
@macartur and @beraldoleal, it would be nice to figure out when a network path is considered "stable". For example, sometimes what happens in production is an interface or fiber start flapping, which creates a lot of ups and downs and sometimes in a short time period. So, even when we don't have the backup_path feature implemented yet, the primary link should be considered back as active only if it's actually stable. What I have seen so far is that other controllers implement this functionality with a kind of histeresis or a timer like wait for X secs before being considered active again, and this timer the user always have control of it, if they want it or not.

**Comment by viniciusarcanjo** [comment]
@beraldoleal and @macartur, regarding this link stable functionality, do you think this should be handled separately in another issue?
