### ISSUE TITLE
Add PortStatus Events listeners to update EVC status

### ISSUE THREAD

**Issue by viniarck** [kytos/mef_eline#34]
This is to address the asynchronous part of requirements on #26. To implement, looks like we could either listen to `'.*.switch.interface.up|down` or `.*.switch.interface.up|down`. One corner case to watch for is the NNI interface (which is connected to the host), this interface won't be considered a link because of lack of LLDP running on the host, so we'll probably have to use the `.*.switch.interface.up|down` events anyway.

**Comment by ajoaoff** [comment]
Do to this, events were created on `topology`, so it listens to `kytos/topology.link_up|down`. It is done in commit 23e0e1746.
