### ISSUE TITLE
RESTful API methods to remove all EVCs and remove specific EVC

### ISSUE THREAD

**Issue by viniarck** [kytos/mef_eline#35]
These are the only two points remaining on issue #8, remove all and remove specific EVC id, I'm creating a new issue since the original issue has been resolved partially on other commits. I believe this way it'll be easier to review and merge these remove methods.

**Comment by viniarck** [comment]
@beraldoleal and @macartur have you had the chance to take a look on my previous comment on this issue? I think we'll need this merged before someone starts addressing the EVC remove functionality.

**Comment by beraldoleal** [comment]
Yes, @viniarck  I took a look, but I think that we can do better.

Today `flow_manager` accepts POST + 'delete' args. But we should try to use there the DELETE method instead.

**Comment by viniarck** [comment]
@beraldoleal do you mean refactor this method https://github.com/kytos/flow_manager/blob/master/main.py#L61-L68 to support the actual HTTP DELETE method?

**Comment by beraldoleal** [comment]
@viniarck sorry for this delay. Yes this method. So, flow_manager should support DELETE flows and mef_eline should use this method in order to delete flows.

Also we should use the flow cookie in order to set an ID on each flow of a circuit. This way would be easy to delete them.

@ajoaoff is working on this.

**Comment by viniarck** [comment]
OK. Thanks @ajoaoff, I'm assigning this to you then.

**Comment by ajoaoff** [comment]
The `DELETE` method for a specific EVC was created in https://github.com/kytos/mef_eline/commit/96a15dc9595e4b152dcbed74873cb752da90777b#diff-5bc02cefb3ea9e27f1a6776eabd1935d , but we still do not have a method to delete all the EVCs at once.

**Comment by jab1982** [comment]
I suggest that we don't create one to avoid accidents.

**Comment by ajoaoff** [comment]
I was reading the documentation on `DELETE` method, and it is not recomended to use this method to delete all the items. The best way to do this is the client application to perform a `GET` to retrieve the list of all EVCs and then call `DELETE` on each EVC.
I think this issue should be closed.
