### ISSUE TITLE
Support scheduling of specific routines and time intervals

### ISSUE THREAD

**Issue by beraldoleal** [kytos/mef_eline#44]
Such as _every_night_, _every_tuesday_, _every_day_from_2am_to_5pm_, and others

**Comment by macartur** [comment]
This was implemented in the class [CircuitScheduler](https://github.com/kytos/mef_eline/blob/master/scheduler.py#L9).

This class support:  
  schedule with run_time, 
  schedule with crontab style
  schedule with interval

**Comment by beraldoleal** [comment]
@macartur, @ajoaoff told us that the flows deployment is not working anymore. I'm reopening this issue.

**Comment by ajoaoff** [comment]
See issue #103 .
