### ISSUE TITLE
Review mef_eline documentation endpoints

### ISSUE THREAD

**Issue by beraldoleal** [kytos/mef_eline#47]
We NEED to update the documentation to describe what we have implemented.

**Comment by beraldoleal** [comment]
@llgoncalves what the status here?

**Comment by hdiogenes** [comment]
In https://napps.kytos.io/kytos/mef_eline, REST API documentation, we need to list everything that is currently implemented.

**Comment by beraldoleal** [comment]
POST /v1/kytos/mef_eline/
GET /v1/kytos/mef_eline/
GET /v1/kytos/mef_eline/{circuit_id}/
DELETE /v1/kytos/mef_eline/{circuit_id}/
PATCH/PUT /v1/kytos/mef_eline/{circuit_id}/

**Comment by rmotitsuki** [comment]
Review OK. Missing only the DELETE method related to issue # 35
