### ISSUE TITLE
Validate all JSON fields in a circuit request

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/mef_eline#5]
As described in the [Topology Improvement Blueprint](https://github.com/kytos/kytos/blob/master/docs/blueprints/EP013.rst).

**Comment by viniciusarcanjo** [comment]
I'm waiting for most PRs #27 - #29 to be merged to push the commit to fix this. I'll extend the validation to the other attributes as well.

**Comment by macartur** [comment]
I will close this issue, a basic validation is already  [implemented](https://github.com/kytos/mef_eline/blob/master/models.py#L85).
