### ISSUE TITLE
Error 500 in POST without parameters

### ISSUE THREAD

**Issue by ajoaoff** [kytos/mef_eline#55]
The request to create an EVC (`POST /api/kytos/mef_eline/v2/evc`) is returning a code 500 but it should return 400.
From the log, it is possible to notice that there is no check if the paramenters are passed.

**Comment by beraldoleal** [comment]
@ajoaoff can you provide the exact POST parameters? Or more detailed info?

**Comment by ajoaoff** [comment]
I sent a POST without parameters.
