### ISSUE TITLE
Add 'available VLANs' to links

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/mef_eline#6]
Based on available VLANs for each interface of the link, defined in the controller.

**Comment by beraldoleal** [comment]
@viniciusarcanjo can you confirm, please if  available_vlans in a link is a union or a intersection. I'm not sure, but if a link is made of two interfaces, the available vlans in a link should be the intersection of available vlans on both interfaces, right ?

**Comment by viniciusarcanjo** [comment]
@beraldoleal right. It's an intersection. If we were not to use an intersection that would mean we would have to have more VLANs translations in place (on each interface that belongs to this link), and using different VLANs on the same link is an anti-pattern in networking.

**Comment by viniciusarcanjo** [comment]
@macartur this fix looks solid to me. +1 

Thanks
