### ISSUE TITLE
Modify the EVC creation to use specific links

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/mef_eline#9]

**Comment by viniarck** [comment]
@beraldoleal This issue even though it is under issue #4 (epic), I believe we won't have enough time to deliver on 2018.1b3, should we move this issue #9 from the epic?

**Comment by macartur** [comment]
The class [EVC](https://github.com/kytos/mef_eline/blob/master/models.py#L166) already have a primary_path and backup_path attributes that can be send by request.
